config/routes.rb
RemotelyObservedTreatment::Application.routes.draw do

  devise_for :admins, controllers: { registrations: :registrations,
                                     sessions: :sessions }

  devise_for :patients, controllers: { registrations: :registrations,
                                       sessions: :sessions }

  resources :reward_rules
  resources :side_effects
  resources :medicines
  resources :pill_sequences do
    collection do
      get 'default'
    end
  end

  resources :admins
  resources :patients do
    resources :records do
      member do
        post :upload_video
        post :process_video
      end
    end
    resources :schedules
    resources :pill_times
    resources :wallet_transactions

        resource :download, only: [:show]
    get "invoice", to: 'downloads#invoice'

    get "report", to: 'downloads#report'

    get "invoices", to: 'patients#invoices'

    get "reports", to: 'patients#reports'

  end

  resources :records, only: [:index, :show] do
    resources :grades
  end

  resources :alerts

  resources :notifications
  resources :applogs

  get '/dashboard', to: 'dashboard#index'
  get '/submission', to: 'dashboard#submission'
  get '/grading(/:sequence_id)', to: 'dashboard#grade', as: 'grading'
  get '/info', to: 'dashboard#additional_info'
  get '/help', to: 'faq#help'
  get '/feedback', to: 'faq#feedback'
  get '/wallet_balance_for_patient/:patient_id', to: 'wallet_balances#show'
  get '/wallets', to: 'patients#wallets'

  get '/calendar/:month/:year', to: 'patients#show_calendar'

  get 'patients/:id/record', to: 'patients#record'

  get '/key', to: 'dashboard#key'  #return decryption key

  root to: 'home#index'

end

app/models/side_effect.rb
# == Schema Information
#
# Table name: side_effects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SideEffect < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :presence => true

  has_and_belongs_to_many :records
end

app/controllers/side_effects_controller.rb
class SideEffectsController < ApplicationController
  before_filter :authenticate_admin_and_patient!, only: [:index]
  before_filter :authenticate_admin!, except: [:index]

  # GET /side_effects
  # GET /side_effects.json
  def index
    @side_effects = SideEffect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json do
        if params.key?(:key) && ['updated_at'].include?(params[:key])
          render json: @side_effects, only: params[:key]
        else
          render json: @side_effects
        end
      end
    end
  end

  # GET /side_effects/1
  # GET /side_effects/1.json
  def show
    @side_effect = SideEffect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @side_effect }
    end
  end

  # GET /side_effects/new
  # GET /side_effects/new.json
  def new
    @side_effect = SideEffect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @side_effect }
    end
  end

  # GET /side_effects/1/edit
  def edit
    @side_effect = SideEffect.find(params[:id])
  end

  # POST /side_effects
  # POST /side_effects.json
  def create
    @side_effect = SideEffect.new(params[:side_effect])

    respond_to do |format|
      if @side_effect.save
        format.html { redirect_to @side_effect, notice: 'Side effect was successfully created.' }
        format.json { render json: @side_effect, status: :created, location: @side_effect }
      else
        format.html { render action: "new" }
        format.json { render json: @side_effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /side_effects/1
  # PUT /side_effects/1.json
  def update
    @side_effect = SideEffect.find(params[:id])

    respond_to do |format|
      if @side_effect.update_attributes(params[:side_effect])
        format.html { redirect_to @side_effect, notice: 'Side effect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @side_effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /side_effects/1
  # DELETE /side_effects/1.json
  def destroy
    @side_effect = SideEffect.find(params[:id])
    @side_effect.destroy

    respond_to do |format|
      format.html { redirect_to side_effects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/side_effects_helper.rb
module SideEffectsHelper
end

app/views/side_effects/_form.html.erb
<%= simple_form_for(@side_effect) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/side_effects/edit.html.erb
<h1><%= t(:editing_side_effect)%></h1>

<%= render 'form' %>

<%= link_to t(:show), @side_effect %> |
<%= link_to t(:back), side_effects_path %>

app/views/side_effects/index.html.erb
<h1><%= t(:side_effect_definitions)%></h1>

<p><%= link_to t(:add_new_side_effect_definition), new_side_effect_path %></p>

<% if @side_effects.empty? %>
  <p><%= t(:there_is_no_side_effect)%></p>
<% else %>

<table class="fullwidth">
  <tr>
    <th><%= t(:name)%></th>
    <th><%= t(:description)%></th>
    <th></th>
    <th></th>
  </tr>

<% @side_effects.each do |side_effect| %>
  <tr>
    <td><%= side_effect.name %></td>
    <td><%= side_effect.description %></td>
    <td><%= link_to t(:edit), edit_side_effect_path(side_effect) %></td>
    <td><%= link_to t(:destroy), side_effect, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
  </tr>
<% end %>
</table>

<% end %>

app/views/side_effects/new.html.erb
<h1><%= t(:add_new_side_effect_definition)%></h1>

<%= render 'form' %>

<%= link_to t(:back), side_effects_path %>

app/views/side_effects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t(:name)%>:</b>
  <%= @side_effect.name %>
</p>

<p>
  <b><%= t(:description)%>:</b>
  <%= @side_effect.description %>
</p>


<%= link_to t(:edit), edit_side_effect_path(@side_effect) %> |
<%= link_to t(:back), side_effects_path %>