config/routes.rb
RemotelyObservedTreatment::Application.routes.draw do

  devise_for :admins, controllers: { registrations: :registrations,
                                     sessions: :sessions }

  devise_for :patients, controllers: { registrations: :registrations,
                                       sessions: :sessions }

  resources :reward_rules
  resources :side_effects
  resources :medicines
  resources :pill_sequences do
    collection do
      get 'default'
    end
  end

  resources :admins
  resources :patients do
    resources :records do
      member do
        post :upload_video
        post :process_video
      end
    end
    resources :schedules
    resources :pill_times
    resources :wallet_transactions

        resource :download, only: [:show]
    get "invoice", to: 'downloads#invoice'

    get "report", to: 'downloads#report'

    get "invoices", to: 'patients#invoices'

    get "reports", to: 'patients#reports'

  end

  resources :records, only: [:index, :show] do
    resources :grades
  end

  resources :alerts

  resources :notifications
  resources :applogs

  get '/dashboard', to: 'dashboard#index'
  get '/submission', to: 'dashboard#submission'
  get '/grading(/:sequence_id)', to: 'dashboard#grade', as: 'grading'
  get '/info', to: 'dashboard#additional_info'
  get '/help', to: 'faq#help'
  get '/feedback', to: 'faq#feedback'
  get '/wallet_balance_for_patient/:patient_id', to: 'wallet_balances#show'
  get '/wallets', to: 'patients#wallets'

  get '/calendar/:month/:year', to: 'patients#show_calendar'

  get 'patients/:id/record', to: 'patients#record'

  get '/key', to: 'dashboard#key'  #return decryption key

  root to: 'home#index'

end

app/models/medicine.rb
# == Schema Information
#
# Table name: medicines
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Medicine < ActiveRecord::Base
  attr_accessible :description, :name

  validates :name, :presence => true

  has_and_belongs_to_many :pill_times
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_filter :authenticate_admin_and_patient!, only: [:index]
  before_filter :authenticate_admin!, except: [:index]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medicines }
      format.csv
    end
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/new
  # GET /medicines/new.json
  def new
    @medicine = Medicine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/1/edit
  def edit
    @medicine = Medicine.find(params[:id])
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(params[:medicine])

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render json: @medicine, status: :created, location: @medicine }
      else
        format.html { render action: "new" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medicines/1
  # PUT /medicines/1.json
  def update
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      if @medicine.update_attributes(params[:medicine])
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine = Medicine.find(params[:id])
    @medicine.destroy

    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= simple_form_for(@medicine) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1><%= t(:editing_medicine)%></h1>

<%= render 'form' %>

<%= link_to t(:show), @medicine %> |
<%= link_to t(:back), medicines_path %>

app/views/medicines/index.html.erb
<h1><%= t(:medicines)%></h1>

<p><%= link_to t(:add_new_medicine), new_medicine_path %></p>

<% if @medicines.empty? %>
  <p><%= t(:there_is_no_medicines)%></p>
<% else %>

<table class="fullwidth">
  <tr>
    <th><%= t(:name)%></th>
    <th><%= t(:description)%></th>
    <th></th>
    <th></th>
  </tr>

<% @medicines.each do |medicine| %>
  <tr>
    <td><%= medicine.name %></td>
    <td><%= medicine.description %></td>
    <td><%= link_to t(:edit), edit_medicine_path(medicine) %></td>
    <td><%= link_to t(:destroy), medicine, method: :delete, data: { confirm: t(:are_you_sure) } %></td>
  </tr>
<% end %>
</table>

<% end %>

app/views/medicines/new.html.erb
<h1><%= t(:add_new_medicine)%></h1>

<%= render 'form' %>

<%= link_to t(:back), medicines_path %>

app/views/medicines/show.html.erb
<p>
  <b><%= t(:name)%>:</b>
  <%= @medicine.name %>
</p>

<p>
  <b><%= t(:description)%>:</b>
  <%= @medicine.description %>
</p>


<%= link_to t(:edit), edit_medicine_path(@medicine) %> |
<%= link_to t(:back), medicines_path %>