config/routes.rb
RemotelyObservedTreatment::Application.routes.draw do

  devise_for :admins, controllers: { registrations: :registrations,
                                     sessions: :sessions }

  devise_for :patients, controllers: { registrations: :registrations,
                                       sessions: :sessions }

  resources :reward_rules
  resources :side_effects
  resources :medicines
  resources :pill_sequences do
    collection do
      get 'default'
    end
  end

  resources :admins
  resources :patients do
    resources :records do
      member do
        post :upload_video
        post :process_video
      end
    end
    resources :schedules
    resources :pill_times
    resources :wallet_transactions

        resource :download, only: [:show]
    get "invoice", to: 'downloads#invoice'

    get "report", to: 'downloads#report'

    get "invoices", to: 'patients#invoices'

    get "reports", to: 'patients#reports'

  end

  resources :records, only: [:index, :show] do
    resources :grades
  end

  resources :alerts

  resources :notifications
  resources :applogs

  get '/dashboard', to: 'dashboard#index'
  get '/submission', to: 'dashboard#submission'
  get '/grading(/:sequence_id)', to: 'dashboard#grade', as: 'grading'
  get '/info', to: 'dashboard#additional_info'
  get '/help', to: 'faq#help'
  get '/feedback', to: 'faq#feedback'
  get '/wallet_balance_for_patient/:patient_id', to: 'wallet_balances#show'
  get '/wallets', to: 'patients#wallets'

  get '/calendar/:month/:year', to: 'patients#show_calendar'

  get 'patients/:id/record', to: 'patients#record'

  get '/key', to: 'dashboard#key'  #return decryption key

  root to: 'home#index'

end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id                      :integer          not null, primary key
#  message                 :string(255)
#  sent                    :boolean          default(FALSE)
#  send_at                 :datetime
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  receiver                :string(255)
#  patient_id              :integer
#  notification_service_id :integer
#

class Notification < ActiveRecord::Base

  attr_accessible :receiver, :message, :send_at, :sent,
                  :patient_id, :notification_service_id

  # validations
  validates :receiver, presence: true
  validates :message,  presence: true, length: { in: 3..140 }
  validates :patient_id,  presence: true
  validates :notification_service_id, presence: true
  validate do
    if receiver.nil? && notification_service.service == 'Sms'
      errors.add(:notification_service_id, "No phone number configured")
    end
  end

  # relations
  belongs_to :patient
  belongs_to :notification_service

  # scopes
  scope :waiting, -> { where(sent: false) }
  scope :to_send, -> { waiting.where('send_at <= ?', Time.zone.now) }

  # delegate_to
  delegate :service, to: :notification_service
  delegate :fullname, to: :patient

  # hooks
  before_validation { self.receiver = patient.send("#{service.downcase}_id") }
  before_create -> { send_at = Time.zone.now if send_at.blank? }

  # paginate
  self.per_page = 10

  # Public: send current notification
  # Returns nothing.
  def deliver
    return if sent?

    begin
      provider = "#{service.capitalize}Service".constantize
      provider.new.send(receiver, message)

      update_attributes(sent: true)
    rescue NameError
      false
    end
  end

  # Public: get a list of patients who need push notify
  #
  # service - a NotificationService instance
  # options - options
  #
  # Return an object at different timing, with patients' mist_ids
  def self.on_pill_times(service, options = {})
    baskets = {}
    # initial baskets of each time slot
    time_slots.each { |time| baskets[time.to_s] = [] }

    # TODO optimize query
    service.patients
           .with_active_schedule
           .find_each(batch_size: 100) do |patient|
             time = patient.find_pill_notification(time_slots)
             receiver = options[:id] ? patient.send(options[:id]) : patient
             baskets[time.to_s].push(receiver) if time && receiver
           end

    baskets
  end

  private

  # TODO change this to be flexible
  def self.time_slots
    [30.minutes, 15.minutes, 0.minutes, -30.minutes, -1.hour, -2.hour]
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_admin!

  # GET /notifications
  # GET /notifications.json
  def index
    @filter = FilterPresenter.new(['waiting', 'all'], 'waiting')
    @filter.current = params[:filter]
    @notifications = Notification.order('send_at DESC')
                                 .page(params[:page])
                                 .send(@filter.active)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notificationss }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    # TODO support multiple receivers
    @notification = Notification.new(patient_id: params[:to])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @service = NotificationService.find(params[:notification][:notification_service_id])
    @notification = @service.notifications.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification,
                      notice: 'Notification was successfully created.'  }
        format.json { render json: @notification,
                             status: :created,
                             location: @notification }
      else
        format.html { render action: 'new' }
        format.json { render json: @notification.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification,
                      notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notification.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to(notifications_url) }
      format.json { head :no_content }
    end
  end

end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :patient_id, label: "To Patient", require: true, placeholder: "Input the last digits of MIST_ID, e.g. 100012, input: 12"%>

    <label for="notification_send_at">* To Send At</label>
    <input type="datetime-local" id="notification_send_at" name="notification[send_at]" value="<%= localdatetime @notification.send_at || Time.zone.now %>" >

    <%= f.association :notification_service, include_blank: false %>

    <%= f.input :message, as: :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1><%= t(:edit_notification)%></h1>

<%= render 'form' %>

<%= link_to t(:back), url_for(:back) %>

app/views/notifications/index.html.erb
<h1><%= t(:notifications)%></h1>

<p>
  <%= link_to t(:create_new_notification), new_notification_path %>
</p>

<%# display_filters(@filter.filters, @filter.active) %>

<% if @notifications.empty? %>
  <p><%= t(:there_is_no_scheduled_notification)%></p>
<% else %>
  <table class="fullwidth">
    <tr>
      <th><%= t(:type)%></th>
      <th><%= t(:receiver)%></th>
      <th><%= t(:time)%></th>
      <th><%= t(:state)%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @notifications.each do |notification| %>
    <tr>
      <td><%= notification.service %></td>
      <td><%= notification.fullname %></td>
      <td><%= localtime notification.send_at %></td>
      <td><%= notification.sent? ? t(:sent) : t(:waiting) %></td>
      <td>
        <%= link_to t(:view), notification %>
      </td>
      <td>
        <%= link_to t(:edit), edit_notification_path(notification) %>
      </td>
      <td>
        <%= link_to 'X', notification, method: :delete, data: { confirm: t(:are_you_sure) } %>
      </td>
    </tr>
  <% end %>
  </table>

  <%= will_paginate @notifications %>
<% end %>

app/views/notifications/new.html.erb
<h1><%= t(:add_new_notification)%></h1>

<%= render 'form' %>

<%= link_to t(:back), url_for(:back) %>

app/views/notifications/show.html.erb
<h1><%= t(:scheduled_notification)%></h1>

<table>
  <tr>
    <td>
      <b><%= t(:receiver)%>:</b>
    </td>
    <td>
      <%= @notification.fullname %>
    </td>
    <td>
      <b><%= t(:deliver_id)%>:</b>
    </td>
    <td>
      <%= @notification.receiver %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t(:type)%></b>
    </td>
    <td>
      <%= @notification.service %>
    </td>
    <td>
      <b><%= t(:to_send_at)%></b>
    </td>
    <td>
      <%= localtime @notification.send_at %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t(:state)%>:</b>
    </td>
    <td colspan="3">
      <%= @notification.sent ? t(:sent) : t(:waiting) %>
    </td>
  </tr>
  <tr>
    <td>
      <b><%= t(:message)%>:</b>
    </td>
    <td colspan="3">
      <%= @notification.message %>
    </td>
  </tr>
</table>

<%= link_to t(:edit), edit_notification_path(@notification) %> |
<%= link_to t(:back), notifications_path %>