config/routes.rb
RemotelyObservedTreatment::Application.routes.draw do

  devise_for :admins, controllers: { registrations: :registrations,
                                     sessions: :sessions }

  devise_for :patients, controllers: { registrations: :registrations,
                                       sessions: :sessions }

  resources :reward_rules
  resources :side_effects
  resources :medicines
  resources :pill_sequences do
    collection do
      get 'default'
    end
  end

  resources :admins
  resources :patients do
    resources :records do
      member do
        post :upload_video
        post :process_video
      end
    end
    resources :schedules
    resources :pill_times
    resources :wallet_transactions

        resource :download, only: [:show]
    get "invoice", to: 'downloads#invoice'

    get "report", to: 'downloads#report'

    get "invoices", to: 'patients#invoices'

    get "reports", to: 'patients#reports'

  end

  resources :records, only: [:index, :show] do
    resources :grades
  end

  resources :alerts

  resources :notifications
  resources :applogs

  get '/dashboard', to: 'dashboard#index'
  get '/submission', to: 'dashboard#submission'
  get '/grading(/:sequence_id)', to: 'dashboard#grade', as: 'grading'
  get '/info', to: 'dashboard#additional_info'
  get '/help', to: 'faq#help'
  get '/feedback', to: 'faq#feedback'
  get '/wallet_balance_for_patient/:patient_id', to: 'wallet_balances#show'
  get '/wallets', to: 'patients#wallets'

  get '/calendar/:month/:year', to: 'patients#show_calendar'

  get 'patients/:id/record', to: 'patients#record'

  get '/key', to: 'dashboard#key'  #return decryption key

  root to: 'home#index'

end

app/controllers/wallet_transactions_controller.rb
class WalletTransactionsController < ApplicationController
  before_filter :authenticate_admin!


  before_filter :set_patient, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  before_filter :set_wallet_transaction, only: [:show, :edit, :update, :destroy]
  def set_wallet_transaction
    @patient = Patient.find(params[:patient_id])
    @wallet_transaction = @patient.wallet_transactions.find(params[:id])
  end

  # GET patient/:patient_id/wallet_transactions
  # GET patient/:patient_id/wallet_transactions.json
  def index
    @wallet_transactions = @patient.wallet_transactions.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wallet_transactions }
    end
  end

  # GET patient/:patient_id/wallet_transactions/1
  # GET patient/:patient_id/wallet_transactions/1.json
  def show
    @wallet_transactions = @patient.wallet_transactions.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wallet_transactions }
    end
  end

  # GET patient/:patient_id/wallet_transactions/new
  # GET patient/:patient_id/wallet_transactions/new.json
  def new
    @wallet_transaction = @patient.wallet_transactions.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wallet_transaction }
    end
  end

  # GET patient/:patient_id/wallet_transactions/1/edit
  def edit
    #@wallet_transaction = WalletTransaction.find(params[:id])
  end

  # POST /wallet_transactions
  # POST /wallet_transactions.json
  def create
    @wallet_transaction = @patient.wallet_transactions.new(params[:wallet_transaction])

    respond_to do |format|
      if @wallet_transaction.save
        format.html { redirect_to [@patient, @wallet_transaction], notice: 'Transaction was successfully saved.' }
        format.json { render json: [@patient, @wallet_transaction], status: :created, location: @wallet_transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wallet_transactions/1
  # PUT /wallet_transactions/1.json
  def update
    respond_to do |format|
      if @wallet_transaction.update_attributes(params[:wallet_transaction])
        format.html { redirect_to [@patient, @wallet_transaction], notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wallet_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_transactions/1
  # DELETE /wallet_transactions/1.json
  def destroy
    @wallet_transaction.destroy

    respond_to do |format|
      format.html { redirect_to patient_wallet_transactions_url(patient) }
      format.json { head :no_content }
    end
  end

end

app/views/wallet_transactions/_for_a_patient.html.erb
<table class="fullwidth">
  <tr>
    <th><%= t(:time)%></th>
    <th><%= t(:amount)%></th>
    <th><%= t(:balance)%></th>
  </tr>
  <% balance = 0 %>
  <% @patient.wallet_transactions.each do |t|
      balance += t.amount
     %>
  <tr>
    <td><%= Ptime.to_human_readable(t.time) %></td>
    <td><%= number_to_currency(t.amount, :unit => '$') %></td>
    <td><%= number_to_currency(balance, :unit => '$') %></td>
  </tr>
  <% end %>
</table>

app/views/wallet_transactions/_form.html.erb
<div>
  Patient <%= @patient.fullname %> (<%= @patient.mist_id %>) has a balance of <b><%= number_to_currency(@patient.wallet_balance) %></b>.
</div>
<div>
How much do you want to pay?
</div>
<%= simple_form_for([@patient, @wallet_transaction]) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :amount, :input_html => { :value => number_to_currency(@patient.wallet_balance, unit: "") } %></div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/wallet_transactions/edit.html.erb
<h1><%= t(:editing_wallet_transaction)%></h1>

<%= render 'form' %>

<%= link_to t(:show), patient_wallet_transaction_path(@patient, @wallet_transaction) %> |
<%= link_to t(:back), patient_wallet_transactions_path(@patient) %>

app/views/wallet_transactions/index.html.erb
<h1>Wallet Transactions for <%= @patient.fullname %></h1>
<% @patient.update_wallet %>

<h3>Current Balance: <%= number_to_currency(@patient.wallet_balance) %> <%= link_to "pay", new_patient_wallet_transaction_path(@patient), {class: 'button small'} %> </h3>

<table class="fullwidth" id="record_list">
  <thead>
    <th><%= t(:created_at)%></th>
    <th><%= t(:amount)%></th>
  </thead>
  <tbody>
    <% @patient.wallet_transactions.each do |t| %>
  <tr>
    <td><%= Ptime.to_human_readable(t.created_at) %></td>
    <td><%= number_to_currency(t.amount, :unit => '$') %></td>
  </tr>
  <% end %>
</tbody>
</table>

<%= link_to "View All Wallets", wallets_path %>

app/views/wallet_transactions/new.html.erb
<h1><%= t(:add_new_wallet_transaction)%></h1>

<%= render 'form' %>

<%= link_to t(:back), patient_wallet_transactions_path(@patient) %>

app/views/wallet_transactions/show.html.erb
<p id="notice"><%= notice %></p>

On <%= Ptime.to_human_readable(@wallet_transaction.created_at) %>, the patient <%= @patient.fullname %> was paid <%= number_to_currency(@wallet_transaction.amount) %>.
</h3>
<%= link_to 'Edit', edit_patient_wallet_transaction_path(@patient, @wallet_transaction) %> |
<%= link_to 'Back', patient_wallet_transactions_path %>